version: '3.8'

services:
  app:
    build: .
    command:
      - "/usr/src/app/start.sh"
    stdin_open: true
    tty: true
    image: observerly/celerity:latest
    container_name: observerly_celerity
    volumes: 
      - ./:/usr/src/app
    env_file:
      - .env